DROP TABLE IF EXISTS tags_blacklist;
CREATE TABLE tags_blacklist (
    tag VARCHAR(255)
);

INSERT INTO tags_blacklist (tag) VALUES
    ('algoritmos'),
	('array'),
    ('animación'),
    ('arreglos'),
    ('aplicación-web'),
    ('base-de-datos'),
    ('batch'),
    ('boton'),
    ('button'),
    ('buscador'),
    ('checkbox'),
    ('combobox'),
    ('datepicker'),
    ('depuración'),
    ('estructuras-de-datos'),
    ('fecha'),
    ('formularios'),
    ('funciones'),
    ('gridview'),
    ('imagen'),
    ('interfaz-gráfica'),
    ('list'),
    ('loops'),
    ('manejo-de-memoria'),
    ('map'),
    ('matemáticas'),
    ('matrices'),
    ('mobile'),
    ('mvc'),
    ('object'),
    ('optimización'),
    ('patrones-de-diseño'),
    ('poo'),
    ('plugin'),
    ('rendimiento'),
    ('revisión-de-código'),
    ('scroll'),
    ('servicio'),
    ('timer'),
    ('trigger'),
    ('try-catch'),
    ('url'),
    ('webservice')
;
